# Generated by Django 5.2.4 on 2025-08-08 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='立場名')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_data',
            field=models.DateField(default='1990-01-01', verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.position', verbose_name='立場'),
        ),
    ]
