# Generated by Django 5.2.4 on 2025-08-05 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=50, verbose_name='店舗名')),
                ('address', models.CharField(max_length=200, verbose_name='店舗住所')),
                ('OpenTime', models.TimeField(verbose_name='開店時間')),
                ('CloseTime', models.TimeField(verbose_name='閉店時間')),
                ('holiday', models.CharField(blank=True, max_length=100, null=True, verbose_name='定休日')),
                ('payment', models.CharField(max_length=100, verbose_name='支払い方法')),
                ('genre', models.ManyToManyField(to='store.genre', verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_images/', verbose_name='店舗写真')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.store')),
            ],
        ),
    ]
