# Generated by Django 5.2.5 on 2025-08-08 18:04


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50, verbose_name='店舗名')),
                ('address', models.CharField(max_length=200, verbose_name='店舗住所')),
                ('tell', models.CharField(default='000-0000-0000', max_length=15, verbose_name='電話番号')),
                ('open_time', models.TimeField(verbose_name='開店時間')),
                ('close_time', models.TimeField(verbose_name='閉店時間')),
                ('holiday', models.CharField(blank=True, max_length=100, null=True, verbose_name='定休日')),
                ('payment', models.CharField(max_length=100, verbose_name='支払い方法')),
                ('genres', models.ManyToManyField(to='store.genre', verbose_name='ジャンル')),
                ('stamp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stamps.stamp', verbose_name='スタンプ情報')),
            ],
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stores/images/', verbose_name='店舗写真')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.store')),
            ],
        ),
    ]
