# Generated by Django 5.2.4 on 2025-08-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(upload_to='media/store_images/', verbose_name='店舗写真'),
        ),
    ]
