# Generated by Django 5.2.4 on 2025-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_storeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(upload_to='stores/images/', verbose_name='店舗写真'),
        ),
    ]
