# Generated by Django 5.2.5 on 2025-08-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('business_hours', models.CharField(blank=True, max_length=100, verbose_name='営業時間')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
            ],
        ),
    ]
