# Generated by Django 5.2.4 on 2025-08-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storeimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='CloseTime',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='OpenTime',
            new_name='open_time',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='StoreName',
            new_name='store_name',
        ),
    ]
