# Generated by Django 5.2.4 on 2025-08-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_rename_closetime_store_close_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReplyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interview/reply_images/', verbose_name='回答画像')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='インタビューのお題')),
                ('description', models.TextField(verbose_name='インタビューの詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(verbose_name='お題への回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答時間')),
                ('store_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_reply', to='store.store', verbose_name='店舗情報')),
                ('image', models.ManyToManyField(blank=True, to='interview.interviewreplyimage', verbose_name='回答画像')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='interview.interviewtopic', verbose_name='お題')),
            ],
        ),
    ]
